### ISSUE TITLE
Profile Docker image build

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-devops#20]
### Backgroud

I'd like to "profile" a docker build. The ideal output would include elapsed time, download size, and final layer size for every command in the Dockerfile. End goal is to find the best optimizations for Tutor's Dockerfiles without relying purely on my hunches about what I believe are the slowest parts.

### Subtasks

- [ ] Profile & analyze the build for `tutor images build openedx` and `tutor dev dc build lms`, which build the opendx and openedx-dev images, respectively.
- [ ] Link to any profiling artifacts here
- [ ] Preate follow-up tickets for applying optimizations and/or diving deeper into analysis.
