### ISSUE TITLE
Move artifacts outside of edx-platform in Tutor's openedx image

### ISSUE THREAD

**Issue by kdmccormick** [openedx/wg-devops#22]
### Background

This is a sub-task of https://github.com/openedx/wg-developer-experience/issues/146.

**The problem:** In the openedx image, static assets are collected & compiled into [several sub-directories of /openedx/edx-platform/](https://github.com/kdmccormick/tutor-contrib-kdmccormick/blob/88ffa2fa799d91d192642ba3ce90564c3b4e2d40/tutorkdmccormick/quickdev.py#L121-L138). So, when you mount your own edx-platform, you override all of those static asset folders. Now, `tutor dev launch` must re-build assets again, which takes a long time and is completely redundant with the assets that you had to download when you downloaded the openedx image. If you forget to do this, then your edx-platform frontend will be broken.

**What we want:** To generate static assets outside of the /openedx/edx-platform directory so that mounting edx-platform does not overwrite them. 

### Tasks

- [x] ~Figure out how to change where static assets go.~ This is very hard.
- [x] ~Figure out how this interacts with a developer's desire to rebuild assets that they have changed. In other words, as a developer, would `tutor dev run --mount=edx-platform openedx-assets build --env=dev` work if I *wanted* to re-run it?~ They should just rebuild
- [ ] In the Docker image build, move the artifacts out of edx-platform
- [ ] In the Docker image build and in mounted-directories.sh, convert edx-platform artifact dirs into symlnks
- [ ] Triumphantly remove the rest of Tutor's mounted-directories.sh task (the parts that regenerate assets and node_modules and egg-infos)

**Comment by kdmccormick** [comment]
This one is still relevant, but I have not had the time to invest in it. If you see this issue and have tutor development experience, please ping me and I'd be happy to help you get started on it.
